#!/usr/bin/env bash

clear
set -euo pipefail

source "./lib/log.sh"
source "./lib/helpers.sh"
source "./lib/prompt.sh"

source "./steps/menu.sh"
source "./steps/mirror.sh"
source "./steps/format_partition.sh"
source "./steps/base_system.sh"
source "./steps/locale.sh"
source "./steps/network.sh"
source "./steps/adduser.sh"
source "./steps/pacman.sh"
source "./steps/swap.sh"
source "./steps/disk.sh"
source "./steps/bootloader.sh"
source "./steps/hibernation.sh"

if [[ "$(id -u)" -ne 0 ]]; then
	error "Script must run with root"
	exit 1
fi

if ! [[ -d /sys/firmware/efi ]]; then
	error "This script only support for EFI firmware"
fi

CPU_VENDOR=$(grep -m 1 'vendor_id' /proc/cpuinfo | awk '{print $3}')

export CPU_VENDOR
export ROOT_MOUNTPOINT="/mnt"
export ESP_MOUNTPOINT="$ROOT_MOUNTPOINT/boot"

timezone
hostname
root_password
username
user_password
kernel
swap_method
if [[ "$SWAP_METHOD" -eq "1" ]]; then
	bootloader
fi
efi_partition
root_partition
swap
summary

if ! [[ "$CONFIRM_INSTALL" =~ [Yy] ]]; then
	clear
	print_color "$GREEN" "Good bye.\n"
	exit 1
fi

clear
setting_mirror
format_partition
base_system
setting_locale
setting_network
adduser
setting_pacman
setting_swap
setting_storage
install_bootloader
setting_storage

umount -Rqlf /mnt
clear
success "Installing arch"
